name: Build Gradle project

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Gradle
        uses: ./.github/actions/build-deps
      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4
      - name: Run gradle build
        run: |
          cd java
          nix develop --command ./gradlew build
